<?php

namespace Acme\Tests\Unity;

use Acme\Application\CreateUserCommand;
use Acme\Application\Service\UserListProjection;
use Acme\Domain\Event\UserCreated;
use Acme\Domain\User;
use Acme\Domain\UserId;
use Acme\Domain\UserName;
use Acme\Infrastructure\InMemoryRepository;
use DI\Container;
use DI\ContainerBuilder;
use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\DriverManager;
use PHPUnit\Framework\TestCase;
use Ramsey\Uuid\Uuid;
use Shared\EventStorage;
use Shared\Repository;
use Shared\SimpleCommandBus;

class UserTest extends TestCase
{
    /**
     * @var Container
     */
    private $container;

    /**
     * @var Repository
     */
    private $repository;

    /**
     * @var Connection
     */
    private $connection;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $builder = new ContainerBuilder();
        $this->container = $builder->build();

        $this->repository = new InMemoryRepository();

        $this->container->set(EventStorage::class, function() {
            return new EventStorage($this->repository);
        });

        $config = new Configuration();
        $connectionParams = array(
            'dbname' => 'simple-event',
            'user' => 'root',
            'password' => 'root',
            'host' => 'simple-event-sourcing-mysql',
            'driver' => 'pdo_mysql',
        );
        $this->connection = DriverManager::getConnection($connectionParams, $config);

    }

    /**
     * @test
     */
    public function new_user()
    {
        $user = new User(
            new UserId(Uuid::uuid4()),
            new UserName('Foo')
        );
        $this->assertEquals('Foo', $user->name());
    }

    /**
     * @test
     */
    public function store_new_user()
    {
        $cb = new SimpleCommandBus($this->container);
        $newUserCommand = new CreateUserCommand('Bar');
        $cb->handle($newUserCommand);

        $storedEvent = unserialize($this->repository->get(0));
        $this->assertInstanceOf(UserCreated::class, $storedEvent);
    }

    /**
     * @test
     */
    public function store_two_new_users()
    {
        $cb = new SimpleCommandBus($this->container);
        $newUserCommand = new CreateUserCommand('Foo');
        $cb->handle($newUserCommand);

        $newUserCommand = new CreateUserCommand('Foz');
        $cb->handle($newUserCommand);

        $storedEvent = unserialize($this->repository->get(0));
        $this->assertInstanceOf(UserCreated::class, $storedEvent);

        $storedEvent = unserialize($this->repository->get(1));
        $this->assertInstanceOf(UserCreated::class, $storedEvent);
    }

    /**
     * @test
     */
    public function replay_user_create_on_projection()
    {
        $cb = new SimpleCommandBus($this->container);
        $newUserOneCommand = new CreateUserCommand('Foo.' . mt_rand());
        $cb->handle($newUserOneCommand);

        $newUserTwoCommand = new CreateUserCommand('Foz.' . mt_rand());
        $cb->handle($newUserTwoCommand);

        $projection = new UserListProjection(new EventStorage($this->repository), $this->connection, []);
        $projection->replayEvent(unserialize($this->repository->get(0)));
        $projection->replayEvent(unserialize($this->repository->get(1)));

        $result = $this->connection->fetchColumn('select name from users where name = ?', [$newUserOneCommand->name]);
        $this->assertEquals($result, $newUserOneCommand->name);

        $result = $this->connection->fetchColumn('select name from users where name = ?', [$newUserTwoCommand->name]);
        $this->assertEquals($result, $newUserTwoCommand->name);

        $this->connection->delete('users', ['name' => $newUserOneCommand->name]);
        $this->connection->delete('users', ['name' => $newUserTwoCommand->name]);
    }
}